services:

  mysql:
    container_name: mysql
    image: mysql:8.0
    command:
      - --general-log=1
      - --general-log-file=/var/log/mysql/query.log
      - --log-output=FILE
    environment:
      MYSQL_DATABASE: app_db
      MYSQL_ROOT_PASSWORD: strong_password
    ports:
      - "3308:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-pstrong_password" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - mysql-data:/var/lib/mysql
  migrations:
    container_name: migrations
    build:
      context: .
      dockerfile: .docker/Dockerfile-migration
    environment:
      GOOSE_DRIVER: "mysql"
      GOOSE_DBSTRING: "root:strong_password@tcp(mysql:3306)/app_db?parseTime=true"

volumes:
  mysql-data:
