// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: proto/schedule.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Schedule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	AidName       string                 `protobuf:"bytes,2,opt,name=aid_name,json=aidName,proto3" json:"aid_name,omitempty"`
	AidPerDay     uint64                 `protobuf:"varint,3,opt,name=aid_per_day,json=aidPerDay,proto3" json:"aid_per_day,omitempty"`
	UserId        uint64                 `protobuf:"varint,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Duration      int64                  `protobuf:"varint,5,opt,name=duration,proto3" json:"duration,omitempty"`
	CreateAt      *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=create_at,json=createAt,proto3" json:"create_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Schedule) Reset() {
	*x = Schedule{}
	mi := &file_proto_schedule_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Schedule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Schedule) ProtoMessage() {}

func (x *Schedule) ProtoReflect() protoreflect.Message {
	mi := &file_proto_schedule_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Schedule.ProtoReflect.Descriptor instead.
func (*Schedule) Descriptor() ([]byte, []int) {
	return file_proto_schedule_proto_rawDescGZIP(), []int{0}
}

func (x *Schedule) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Schedule) GetAidName() string {
	if x != nil {
		return x.AidName
	}
	return ""
}

func (x *Schedule) GetAidPerDay() uint64 {
	if x != nil {
		return x.AidPerDay
	}
	return 0
}

func (x *Schedule) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Schedule) GetDuration() int64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *Schedule) GetCreateAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateAt
	}
	return nil
}

type CreateScheduleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AidName       string                 `protobuf:"bytes,1,opt,name=aid_name,json=aidName,proto3" json:"aid_name,omitempty"`
	AidPerDay     uint64                 `protobuf:"varint,2,opt,name=aid_per_day,json=aidPerDay,proto3" json:"aid_per_day,omitempty"`
	UserId        uint64                 `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Duration      int64                  `protobuf:"varint,4,opt,name=duration,proto3" json:"duration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateScheduleRequest) Reset() {
	*x = CreateScheduleRequest{}
	mi := &file_proto_schedule_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateScheduleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateScheduleRequest) ProtoMessage() {}

func (x *CreateScheduleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_schedule_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateScheduleRequest.ProtoReflect.Descriptor instead.
func (*CreateScheduleRequest) Descriptor() ([]byte, []int) {
	return file_proto_schedule_proto_rawDescGZIP(), []int{1}
}

func (x *CreateScheduleRequest) GetAidName() string {
	if x != nil {
		return x.AidName
	}
	return ""
}

func (x *CreateScheduleRequest) GetAidPerDay() uint64 {
	if x != nil {
		return x.AidPerDay
	}
	return 0
}

func (x *CreateScheduleRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateScheduleRequest) GetDuration() int64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

type KeyValuePair struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyValuePair) Reset() {
	*x = KeyValuePair{}
	mi := &file_proto_schedule_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyValuePair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyValuePair) ProtoMessage() {}

func (x *KeyValuePair) ProtoReflect() protoreflect.Message {
	mi := &file_proto_schedule_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyValuePair.ProtoReflect.Descriptor instead.
func (*KeyValuePair) Descriptor() ([]byte, []int) {
	return file_proto_schedule_proto_rawDescGZIP(), []int{2}
}

func (x *KeyValuePair) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *KeyValuePair) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type CreateScheduleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateScheduleResponse) Reset() {
	*x = CreateScheduleResponse{}
	mi := &file_proto_schedule_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateScheduleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateScheduleResponse) ProtoMessage() {}

func (x *CreateScheduleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_schedule_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateScheduleResponse.ProtoReflect.Descriptor instead.
func (*CreateScheduleResponse) Descriptor() ([]byte, []int) {
	return file_proto_schedule_proto_rawDescGZIP(), []int{3}
}

func (x *CreateScheduleResponse) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CreateScheduleResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetUserScheduleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserScheduleRequest) Reset() {
	*x = GetUserScheduleRequest{}
	mi := &file_proto_schedule_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserScheduleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserScheduleRequest) ProtoMessage() {}

func (x *GetUserScheduleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_schedule_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserScheduleRequest.ProtoReflect.Descriptor instead.
func (*GetUserScheduleRequest) Descriptor() ([]byte, []int) {
	return file_proto_schedule_proto_rawDescGZIP(), []int{4}
}

func (x *GetUserScheduleRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetUserScheduleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Schedules     []uint64               `protobuf:"varint,1,rep,packed,name=schedules,proto3" json:"schedules,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserScheduleResponse) Reset() {
	*x = GetUserScheduleResponse{}
	mi := &file_proto_schedule_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserScheduleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserScheduleResponse) ProtoMessage() {}

func (x *GetUserScheduleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_schedule_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserScheduleResponse.ProtoReflect.Descriptor instead.
func (*GetUserScheduleResponse) Descriptor() ([]byte, []int) {
	return file_proto_schedule_proto_rawDescGZIP(), []int{5}
}

func (x *GetUserScheduleResponse) GetSchedules() []uint64 {
	if x != nil {
		return x.Schedules
	}
	return nil
}

func (x *GetUserScheduleResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetScheduleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ScheduleId    uint64                 `protobuf:"varint,2,opt,name=schedule_id,json=scheduleId,proto3" json:"schedule_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetScheduleRequest) Reset() {
	*x = GetScheduleRequest{}
	mi := &file_proto_schedule_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetScheduleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScheduleRequest) ProtoMessage() {}

func (x *GetScheduleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_schedule_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScheduleRequest.ProtoReflect.Descriptor instead.
func (*GetScheduleRequest) Descriptor() ([]byte, []int) {
	return file_proto_schedule_proto_rawDescGZIP(), []int{6}
}

func (x *GetScheduleRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetScheduleRequest) GetScheduleId() uint64 {
	if x != nil {
		return x.ScheduleId
	}
	return 0
}

type GetDailyScheduleResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	FormattedTimes []string               `protobuf:"bytes,1,rep,name=formatted_times,json=formattedTimes,proto3" json:"formatted_times,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetDailyScheduleResponse) Reset() {
	*x = GetDailyScheduleResponse{}
	mi := &file_proto_schedule_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDailyScheduleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDailyScheduleResponse) ProtoMessage() {}

func (x *GetDailyScheduleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_schedule_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDailyScheduleResponse.ProtoReflect.Descriptor instead.
func (*GetDailyScheduleResponse) Descriptor() ([]byte, []int) {
	return file_proto_schedule_proto_rawDescGZIP(), []int{7}
}

func (x *GetDailyScheduleResponse) GetFormattedTimes() []string {
	if x != nil {
		return x.FormattedTimes
	}
	return nil
}

type GetNextTakingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNextTakingsRequest) Reset() {
	*x = GetNextTakingsRequest{}
	mi := &file_proto_schedule_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNextTakingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNextTakingsRequest) ProtoMessage() {}

func (x *GetNextTakingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_schedule_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNextTakingsRequest.ProtoReflect.Descriptor instead.
func (*GetNextTakingsRequest) Descriptor() ([]byte, []int) {
	return file_proto_schedule_proto_rawDescGZIP(), []int{8}
}

func (x *GetNextTakingsRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetNextTakingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Schedule      []*KeyValuePair        `protobuf:"bytes,1,rep,name=schedule,proto3" json:"schedule,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNextTakingsResponse) Reset() {
	*x = GetNextTakingsResponse{}
	mi := &file_proto_schedule_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNextTakingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNextTakingsResponse) ProtoMessage() {}

func (x *GetNextTakingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_schedule_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNextTakingsResponse.ProtoReflect.Descriptor instead.
func (*GetNextTakingsResponse) Descriptor() ([]byte, []int) {
	return file_proto_schedule_proto_rawDescGZIP(), []int{9}
}

func (x *GetNextTakingsResponse) GetSchedule() []*KeyValuePair {
	if x != nil {
		return x.Schedule
	}
	return nil
}

func (x *GetNextTakingsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_schedule_proto protoreflect.FileDescriptor

const file_proto_schedule_proto_rawDesc = "" +
	"\n" +
	"\x14proto/schedule.proto\x12\bschedule\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc3\x01\n" +
	"\bSchedule\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x19\n" +
	"\baid_name\x18\x02 \x01(\tR\aaidName\x12\x1e\n" +
	"\vaid_per_day\x18\x03 \x01(\x04R\taidPerDay\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\x04R\x06userId\x12\x1a\n" +
	"\bduration\x18\x05 \x01(\x03R\bduration\x127\n" +
	"\tcreate_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\bcreateAt\"\x87\x01\n" +
	"\x15CreateScheduleRequest\x12\x19\n" +
	"\baid_name\x18\x01 \x01(\tR\aaidName\x12\x1e\n" +
	"\vaid_per_day\x18\x02 \x01(\x04R\taidPerDay\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x04R\x06userId\x12\x1a\n" +
	"\bduration\x18\x04 \x01(\x03R\bduration\"6\n" +
	"\fKeyValuePair\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"B\n" +
	"\x16CreateScheduleResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"(\n" +
	"\x16GetUserScheduleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"Q\n" +
	"\x17GetUserScheduleResponse\x12\x1c\n" +
	"\tschedules\x18\x01 \x03(\x04R\tschedules\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"N\n" +
	"\x12GetScheduleRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x1f\n" +
	"\vschedule_id\x18\x02 \x01(\x04R\n" +
	"scheduleId\"C\n" +
	"\x18GetDailyScheduleResponse\x12'\n" +
	"\x0fformatted_times\x18\x01 \x03(\tR\x0eformattedTimes\"0\n" +
	"\x15GetNextTakingsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\"f\n" +
	"\x16GetNextTakingsResponse\x122\n" +
	"\bschedule\x18\x01 \x03(\v2\x16.schedule.KeyValuePairR\bschedule\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xe4\x02\n" +
	"\x0fScheduleService\x12S\n" +
	"\x0eCreateSchedule\x12\x1f.schedule.CreateScheduleRequest\x1a .schedule.CreateScheduleResponse\x12V\n" +
	"\x0fGetUserSchedule\x12 .schedule.GetUserScheduleRequest\x1a!.schedule.GetUserScheduleResponse\x12O\n" +
	"\vGetSchedule\x12\x1c.schedule.GetScheduleRequest\x1a\".schedule.GetDailyScheduleResponse\x12S\n" +
	"\x0eGetNextTakings\x12\x1f.schedule.GetNextTakingsRequest\x1a .schedule.GetNextTakingsResponseB1Z/C:/Users/Andrew/GolandProjects/dolittle2/genrpcb\x06proto3"

var (
	file_proto_schedule_proto_rawDescOnce sync.Once
	file_proto_schedule_proto_rawDescData []byte
)

func file_proto_schedule_proto_rawDescGZIP() []byte {
	file_proto_schedule_proto_rawDescOnce.Do(func() {
		file_proto_schedule_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_schedule_proto_rawDesc), len(file_proto_schedule_proto_rawDesc)))
	})
	return file_proto_schedule_proto_rawDescData
}

var file_proto_schedule_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_schedule_proto_goTypes = []any{
	(*Schedule)(nil),                 // 0: schedule.Schedule
	(*CreateScheduleRequest)(nil),    // 1: schedule.CreateScheduleRequest
	(*KeyValuePair)(nil),             // 2: schedule.KeyValuePair
	(*CreateScheduleResponse)(nil),   // 3: schedule.CreateScheduleResponse
	(*GetUserScheduleRequest)(nil),   // 4: schedule.GetUserScheduleRequest
	(*GetUserScheduleResponse)(nil),  // 5: schedule.GetUserScheduleResponse
	(*GetScheduleRequest)(nil),       // 6: schedule.GetScheduleRequest
	(*GetDailyScheduleResponse)(nil), // 7: schedule.GetDailyScheduleResponse
	(*GetNextTakingsRequest)(nil),    // 8: schedule.GetNextTakingsRequest
	(*GetNextTakingsResponse)(nil),   // 9: schedule.GetNextTakingsResponse
	(*timestamppb.Timestamp)(nil),    // 10: google.protobuf.Timestamp
}
var file_proto_schedule_proto_depIdxs = []int32{
	10, // 0: schedule.Schedule.create_at:type_name -> google.protobuf.Timestamp
	2,  // 1: schedule.GetNextTakingsResponse.schedule:type_name -> schedule.KeyValuePair
	1,  // 2: schedule.ScheduleService.CreateSchedule:input_type -> schedule.CreateScheduleRequest
	4,  // 3: schedule.ScheduleService.GetUserSchedule:input_type -> schedule.GetUserScheduleRequest
	6,  // 4: schedule.ScheduleService.GetSchedule:input_type -> schedule.GetScheduleRequest
	8,  // 5: schedule.ScheduleService.GetNextTakings:input_type -> schedule.GetNextTakingsRequest
	3,  // 6: schedule.ScheduleService.CreateSchedule:output_type -> schedule.CreateScheduleResponse
	5,  // 7: schedule.ScheduleService.GetUserSchedule:output_type -> schedule.GetUserScheduleResponse
	7,  // 8: schedule.ScheduleService.GetSchedule:output_type -> schedule.GetDailyScheduleResponse
	9,  // 9: schedule.ScheduleService.GetNextTakings:output_type -> schedule.GetNextTakingsResponse
	6,  // [6:10] is the sub-list for method output_type
	2,  // [2:6] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_proto_schedule_proto_init() }
func file_proto_schedule_proto_init() {
	if File_proto_schedule_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_schedule_proto_rawDesc), len(file_proto_schedule_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_schedule_proto_goTypes,
		DependencyIndexes: file_proto_schedule_proto_depIdxs,
		MessageInfos:      file_proto_schedule_proto_msgTypes,
	}.Build()
	File_proto_schedule_proto = out.File
	file_proto_schedule_proto_goTypes = nil
	file_proto_schedule_proto_depIdxs = nil
}
